### ISSUE TITLE
Make a blog

### ISSUE THREAD

**Issue by stephlocke** [satRdays/satRdays.github.io#2]
We could do with a blog to post news items, conference updates etc - we can then get this on r-bloggers etc to boost visibility of satRday activities.
- Must have an RSS feed
- Must be able to have a logo and simple theming
- Ideally hosts on github pages

**Comment by stephlocke** [comment]
Hey @jangorecki, I was wondering if you'd be able to give @janmulkens some support whilst he makes a jekyll blog?

@janmulkens: if you work on it inside your own account, then when you're happy we can fork it, put a satrdays url over it. We'll then have a blogmaster team of which you will be one :-)

**Comment by jangorecki** [comment]
Sure, I can try, probably not much cause all I've done on my blog was just a fork this one: https://github.com/barryclark/jekyll-now and update metadata in the config. I wasn't even using any local development environment.

**Comment by JanMulkens** [comment]
@stephlocke, as we talked about, I forked the blog to satrday.github.io/blog
All the options you asked for are apparantly standard in the Jekyll blog.

I've altered the readme.md to include a basic "tutorial" to create basic posts.
But mostly, you'll be wanting to check the official documentation and some markdown cheat sheet (both included as links).

Since the setup is kinda basic right now, please let me know if and when I could be of any more assistance. Although when you go for that theming thing you talked about, I'd be useless :)

**Comment by JanMulkens** [comment]
Also, thanks for the opportunity!
Was the first time I had to work with GitHub this much and in this way, learned quite a bit.

**Comment by stephlocke** [comment]
Could you:
1. Update the master README to tell folks to go to the gh-pages branch
2. I think you need an extra line break for your numbers list to properly indent in your gh-pages README https://github.com/JanMulkens/satRdays-blog/blame/gh-pages/README.md#L14

**Comment by JanMulkens** [comment]
Should be done. (yay my first pull requests!)
Can you verify when you have the time?

**Comment by stephlocke** [comment]
@JanMulkens did a great job. Blog now available at satRdays/blog
